# Generated by Django 3.0.1 on 2019-12-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('website', models.URLField()),
                ('job', models.CharField(choices=[('ST', 'STUDENT'), ('BS', 'BUSINESS MAN'), ('PR', 'PROGRAMMER'), ('ETC', 'ETC')], default='ETC', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
