class Template:
    model_owner = "model_owner"
    detail_view = "detail_view"
    detail_view_u = "detail_view_u"
    detail_view_d = "detail_view_d"
    detail_view_ud = "detail_view_ud"
    all_objects_view = "all_objects_view"
    filter_objects_view = "filter_objects_view"
    user_register_view = "user_register_view"
    user_profile_view = "user_profile_view"
    user_profile_detail_view = "user_profile_detail_view"