# Generated by Django 3.0.3 on 2020-02-04 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('tag', models.TextField(default='')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
